-- MySQL Script generated by MySQL Workbench
-- Thu 18 Apr 2019 04:56:39 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema workshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workshop` DEFAULT CHARACTER SET utf8 ;
USE `workshop` ;

-- -----------------------------------------------------
-- Table `workshop`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `commentary` VARCHAR(300) NULL DEFAULT NULL,
  `mark` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workshop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(60) NULL DEFAULT NULL,
  `name_ua` VARCHAR(60) NULL DEFAULT NULL,
  `surname` VARCHAR(60) NULL DEFAULT NULL,
  `surname_ua` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(60) NOT NULL,
  `phone_number` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workshop`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`request` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_category` VARCHAR(45) NOT NULL,
  `device` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT '',
  `creationDate` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `managerComment` VARCHAR(300) NULL DEFAULT '',
  `customer` INT(11) NOT NULL,
  `manager` INT(11) NULL DEFAULT NULL,
  `master` INT(11) NULL DEFAULT NULL,
  `feedback` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC),
  INDEX `fk_request_user_idx` (`customer` ASC),
  INDEX `fk_request_user1_idx` (`manager` ASC),
  INDEX `fk_request_user2_idx` (`master` ASC),
  INDEX `fk_request_feedback1_idx1` (`feedback` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer`)
    REFERENCES `workshop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `feedback_id`
    FOREIGN KEY (`feedback`)
    REFERENCES `workshop`.`feedback` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `manager_id`
    FOREIGN KEY (`manager`)
    REFERENCES `workshop`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `master_id`
    FOREIGN KEY (`master`)
    REFERENCES `workshop`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workshop`.`request_archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`request_archive` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_category` VARCHAR(45) NOT NULL,
  `device` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT '',
  `creationDate` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `managerComment` VARCHAR(300) NULL DEFAULT '',
  `customer` INT(11) NOT NULL,
  `manager` INT(11) NULL DEFAULT NULL,
  `master` INT(11) NULL DEFAULT NULL,
  `feedback` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
